[tool.isort]
known_third_party = ["pytest", "setuptools"]
profile = "black"
src_paths = ["drinks", "tests"] # Particular for project
skip = [".gitignore"]
extend_skip = [".md", ".json"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]